config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'
  get 'providers/index'
  get 'manufacturer/index'
  get 'devices/index'
  root 'devices#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/device.rb
class Device < ApplicationRecord
end

app/models/manufacturer.rb
class Manufacturer < ApplicationRecord
end

app/models/provider.rb
class Provider < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end
end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  def index
  end
end

app/controllers/manufacturer_controller.rb
class ManufacturerController < ApplicationController
  def index
    @manufacturers = Manufacturer.all
  end
end

app/controllers/providers_controller.rb
class ProvidersController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/helpers/manufacturer_helper.rb
module ManufacturerHelper
end

app/helpers/providers_helper.rb
module ProvidersHelper
end

app/views/categories/index.html.erb
<h1>Categories</h1>

app/views/devices/index.html.erb
<h1>DEVICES</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Midterm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%# <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style>
body {
  margin: 0;
  font-family: Arial, Helvetica, sans-serif;
}

.topnav {
  overflow: hidden;
  background-color: #333;
}

.topnav a {
  float: left;
  color: #f2f2f2;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
  font-size: 17px;
}

.topnav a:hover {
  background-color: #ddd;
  color: black;
}

.topnav a.active {
  background-color: #4CAF50;
  color: white;
}
</style>

  </head>

  <body>
    <div class="topnav">
      <h1>
        <%= link_to 'Devices', root_path %>
      </h1>
      <h1>
        <%= link_to 'manufacturer', manufacturer_index_path %>
      </h1>
      <h1>
        <%= link_to 'Provider', providers_index_path %>
      </h1>
      <h1>
        <%= link_to 'Categories', categories_index_path %>
      </h1>
    </div>
    <%= yield %>
  </body>
</html>

app/views/manufacturer/index.html.erb
<h1>Manufacturer</h1>
<% @manufacturers.each do |manu| %>
<p><%= manu.manufacturerName %></p>
<% end %>

app/views/providers/index.html.erb
<h1>Providers</h1>